## WHAT IS PYTORCH?

https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py<br>
http://python-future.org/compatible_idioms.html

In [2]:
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

import torch

In [4]:
x = torch.empty(5,3)
print(x)

tensor([[9.7347e-39, 9.8265e-39, 1.0102e-38],
        [8.4490e-39, 9.6428e-39, 1.1112e-38],
        [9.5511e-39, 1.0102e-38, 1.0286e-38],
        [1.0194e-38, 9.6429e-39, 9.2755e-39],
        [9.1837e-39, 9.3674e-39, 1.0745e-38]])


In [6]:
x = torch.rand(5,3)
print(x)

tensor([[0.0348, 0.1257, 0.4038],
        [0.9018, 0.3094, 0.7190],
        [0.4269, 0.6289, 0.6978],
        [0.1447, 0.8365, 0.6753],
        [0.8112, 0.0632, 0.9406]])


In [7]:
x = torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [8]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [9]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.0334,  0.1610, -0.3650],
        [-1.0656,  2.1285, -0.2667],
        [ 0.5650, -0.1976, -0.4006],
        [-1.0058, -1.1672,  0.2294],
        [-0.0516, -0.9630, -0.5084]])


In [10]:
print(x.size())

torch.Size([5, 3])


In [11]:
y = torch.rand(5,3)
print(x+y)

tensor([[ 0.7987,  0.7250, -0.2637],
        [-0.7637,  2.3395,  0.5730],
        [ 0.6707,  0.5829,  0.5415],
        [-0.6320, -0.9508,  0.5583],
        [ 0.2833, -0.1562, -0.3306]])


In [12]:
print(torch.add(x,y))

tensor([[ 0.7987,  0.7250, -0.2637],
        [-0.7637,  2.3395,  0.5730],
        [ 0.6707,  0.5829,  0.5415],
        [-0.6320, -0.9508,  0.5583],
        [ 0.2833, -0.1562, -0.3306]])


In [13]:
result = torch.empty(5,3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.7987,  0.7250, -0.2637],
        [-0.7637,  2.3395,  0.5730],
        [ 0.6707,  0.5829,  0.5415],
        [-0.6320, -0.9508,  0.5583],
        [ 0.2833, -0.1562, -0.3306]])


In [14]:
#add x to y
y.add_(x)
print(y)

tensor([[ 0.7987,  0.7250, -0.2637],
        [-0.7637,  2.3395,  0.5730],
        [ 0.6707,  0.5829,  0.5415],
        [-0.6320, -0.9508,  0.5583],
        [ 0.2833, -0.1562, -0.3306]])


Any operation that mutates a tensor in-place is post-fixed with an \_. For example x.copy_(y), x.t_(), will change x.

In [16]:
print(x[:,1]) # Standard Numpy-link indexing second column

tensor([ 0.1610,  2.1285, -0.1976, -1.1672, -0.9630])


In [19]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1, 8) # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())
print(x)
print(y)
print(z)

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
tensor([[-1.9953, -1.8887, -0.1219, -0.0342],
        [ 0.1235, -0.0207, -1.1556, -0.4757],
        [-0.2196,  0.3084, -1.2135, -0.0206],
        [ 0.0336, -0.7646,  0.7504, -0.7963]])
tensor([-1.9953, -1.8887, -0.1219, -0.0342,  0.1235, -0.0207, -1.1556, -0.4757,
        -0.2196,  0.3084, -1.2135, -0.0206,  0.0336, -0.7646,  0.7504, -0.7963])
tensor([[-1.9953, -1.8887, -0.1219, -0.0342,  0.1235, -0.0207, -1.1556, -0.4757],
        [-0.2196,  0.3084, -1.2135, -0.0206,  0.0336, -0.7646,  0.7504, -0.7963]])


In [20]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.9997])
-1.9996951818466187


## NumPy Bridge

In [21]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [22]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [23]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [24]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## CUDA Tensors

In [25]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!
else:
    print("CUDA is not available.")

tensor([-0.9997], device='cuda:0')
tensor([-0.9997], dtype=torch.float64)
